# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: UT CS HCI Lab
email: utcshci@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  We are a research lab at the Department of Computer Science at 
  The University of Texas at Austin. Our long term research goal 
  is to make communication more effective and accessible by embedding 
  machine learning technologies (e.g., Natural Language Processing) 
  into new human interactions.
baseurl: "" # the subpath of your site, e.g. /blog
domain: ut-cs-hci.github.io # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://ut-cs-hci.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: utcshci
github_username: ut-cs-hci

sass:
  style: compressed
  load_paths:
    - node_modules

collections:
  publications:
    output: true
  people:
    output: false
  courses:
    output: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-redirect-from
kramdown:
  toc_levels: 1..2
